server:
  port: 7001

#Eureka配置
eureka:
  instance:
    hostname: localhost  #Eureka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向Eureka注册自己
    fetch-registry: false   #fetch-registry为false表示自己为注册中心
    server-url: #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/