server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  #连接远程仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/keaidekailin/springcloud-config.git    #https

#Eurake
#eureka 客户端配置
eureka:
  client:
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka/ #配置eureka服务端地址
      #集群
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/, http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-config-server  #修改eureka上默认客户端的描述
    prefer-ip-address: true #显示ip地址