#服务配置
server:
  #端口
  port: 8001

#mybatis 配置
mybatis:
  # 实体包
  type-aliases-package: com.liao.springcloud.pojo
  #mybatis 配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  #mapper 配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring 配置
spring:
  application:
    name: springcloud-provider-dept-8001
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root