server:
  port: 8000


dubbo:
  #\u670D\u52A1\u5E94\u7528\u540D
  application:
    name: provider-server
  #\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
  registry:
    address: zookeeper://127.0.0.1:2181
  #\u90A3\u4E9B\u670D\u52A1\u88AB\u6CE8\u518C
  scan:
    base-packages: com.liao.service