server:
  port: 7003
spring:
  application:
    name: 7003
#Eureka配置
eureka:
  instance:
    #为了演示集群，修改C:\Windows\System32\drivers\etc的hosts增加三个
    #127.0.0.1 eureka7001.com
    #127.0.0.1 eureka7002.com
    #127.0.0.1 eureka7003.com
    hostname: eureka7003.com  #Eureka服务端的实例名称
  client:
    register-with-eureka: false  #表示是否向Eureka注册自己
    fetch-registry: false   #fetch-registry为false表示自己为注册中心
    server-url: #监控页面
      #单机版的
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/