server:
  port: 8001

#\u6D88\u8D39\u8005\u66B4\u9732\u81EA\u5DF1\u5F97\u540D\u5B57
dubbo:
  application:
    name: consumer-server
  registry:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.liao.service
  protocol:
    host: 127.0.0.1